### ISSUE TITLE
Feedback from user submitting a session

### ISSUE THREAD

**Issue by thejimbirch** [MidCamp/midcamp#113]
The back to editing link is overlapping with the nav.  See screenshot:

![screenshot-www midcamp org 2018-01-02 12-41-00-440](https://user-images.githubusercontent.com/5177009/34495663-d5b938c6-efbb-11e7-8648-f3fc0791f51b.png)

Also - the image size for the profile image was surprisingly small (30 kb) when I created my new account.  Maybe I just need to optimize my images better :slightly_smiling_face:

**Comment by kthull** [comment]
Those links only happen in the preview state, so I've removed the preview capability on topic content types for now on live. Will file a PR in a bit.

**Comment by kthull** [comment]
Also updated user profile pic to max 250x250/512kb and will add to that PR.
