### ISSUE TITLE
Un-omidcamp Things

### ISSUE THREAD

**Issue by froboy** [MidCamp/midcamp#378]
Switching back to the non-O'midcamp theme breaks things:

> Twig\Error\LoaderError: Template "themes/custom/hatter_base/svg/menu.svg" is not defined in "themes/custom/hatter_base/templates/navigation/menu--main.html.twig" at line 34. in Twig\Loader\ChainLoader->getCacheKey() (line 142 of /app/vendor/twig/twig/src/Loader/ChainLoader.php).

Let's fix these, then put the regular theme back.

**Comment by froboy** [comment]
Resolves #266

**Comment by backlineint** [comment]
@froboy I can take a look at this one.

**Comment by froboy** [comment]
Thanks @backlineint! I think reverting the homepage hatter and colors should be most of it.

**Comment by Brian-Clement** [comment]
@froboy @backlineint apologies, I missed this.  I have a WIP PR at https://github.com/MidCamp/midcamp/pull/380 which can be seen at https://nginx.feature-theme-switching.midcamp-org.us2.amazee.io/.  This just turns the old theme back on and uses a theme switching module to show the green theme on the relevant 2020 pages.

**Comment by froboy** [comment]
Resolved by https://github.com/MidCamp/midcamp/pull/380
