### ISSUE TITLE
Header photo is awesome but on interior pages it’s all dudes. setting position-y to something like 10% could make it better

### ISSUE THREAD

**Issue by froboy** [MidCamp/midcamp#44]
Options: 
https://www.flickr.com/photos/midcamp/23502882578/in/dateposted-public/
https://www.flickr.com/photos/midcamp/37324452232/in/dateposted-public/
https://www.flickr.com/photos/midcamp/23502891088/in/dateposted-public/

**Comment by zendoodles** [comment]
cc @aCyborg
