### ISSUE TITLE
Drupal Planet Feed

### ISSUE THREAD

**Issue by thejimbirch** [MidCamp/midcamp#67]
The site should have a feed that provides a feed for Drupal.org's Planet Drupal.  We have already submitted and been approved using the Drupal 7 site.  The URL needs to be:

https://www.midcamp.org/midcamp-news.xml

The feed should look exactly as it does for in the Drupal 7 site which can be seen here:

https://2017.midcamp.org/midcamp-news.xml

You can copy the settings from this view in the Drupal 7 site:

https://2017.midcamp.org/admin/structure/views/view/drupal_planet/edit

**Comment by froboy** [comment]
Closing as completed.
