### ISSUE TITLE
Messages need to appear on production

### ISSUE THREAD

**Issue by labbydev** [MidCamp/midcamp#72]
It seems like pages are erroring or in some way attempting to give me a message but I cannot see them, assuming this is because messages have been turned off on production.

**Comment by froboy** [comment]
The messages block was in a region that wasn't rendered. I've changed this in https://github.com/MidCamp/midcamp/pull/74/commits/e31bdf706ee4962cb1d102347468a2218095d421

**Comment by labbydev** [comment]
@froboy does that mean that this issue can be closed?

**Comment by kthull** [comment]
@froboy @labbydev this should also go with https://github.com/MidCamp/midcamp/pull/83 so messages can also be styled properly from the classy base theme.
