### ISSUE TITLE
README Start up doc doesn't work

### ISSUE THREAD

**Issue by labbydev** [MidCamp/midcamp#85]
As a user trying to work on this, I would like the `README` to have accurate information on getting up and running correctly. Even though I've had this site up and running before I _always_ have issues get my local up and running. 

For example running `docker-compose up -d` always results in an error:
`ERROR: Couldn't connect to Docker daemon - you might need to run docker-machine start default.` It seems like that line needs to be changed to `amazeeio-cachalot up`. Which I believe is the correct way to bring the machine up, however I'm unfamiliar with the setup to know better. 

** This may be a separate issue** but after running that I get a `503` in browser. So I'm still not sure how to get up and running.

**Comment by froboy** [comment]
Closing as outdated
