### ISSUE TITLE
Topic Type looks out of place on Topic 

### ISSUE THREAD

**Issue by thejimbirch** [MidCamp/midcamp#94]
In the full display of topics, the Topic Type field appears in between that title and the body with no label.  This looks a bit odd.  

<img width="606" alt="screen shot 2017-12-22 at 4 19 01 pm" src="https://user-images.githubusercontent.com/5177009/34314384-d40b450e-e738-11e7-9658-392817e11947.png" style="border: 1px solid #ccc;">

I suggest either removing it or moving it to the bottom with the other metadata (Track).

<img width="568" alt="screen shot 2017-12-22 at 4 56 53 pm" src="https://user-images.githubusercontent.com/5177009/34314416-27d74ffc-e739-11e7-9581-58ed61476443.png" style="border: 1px solid #ccc;">

**Comment by kthull** [comment]
fixed
