### ISSUE TITLE
Update Social Media to match 2018 MidCamp branding

### ISSUE THREAD

**Issue by kthull** [MidCamp/midcamp#97]
Need to update social bios and avatars with new dates and image.

**Comment by thejimbirch** [comment]
Twitter: Logo and header image updated.  Sent a tweet last night.
Facebook: Logo and header image updated. Event posted.
YouTube: Logo and header image updated.
MailChimp: Template made for 2018, the first email is staged, and news post created on-site unpublished.

https://www.midcamp.org/article/buy-ticket-submit-session-and-sponsor-midcamp-2018
